name: Node.js CI

on:
  push:
    paths:
    - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install
      working-directory: client/
      run: npm install
    - name: Test
      working-directory: client/
      run: npm test
      env:
        CI: true
